package cn.totorotec.service.security;

import cn.totorotec.entity.*;

public interface SupportingSystem {

    /**
     * The session parameter, which represents the session identifier,
     * is actually generated by the underlying system.
     *
     *
     * @param user
     * @param session
     * @return
     */
    Session createSession(User user, String session);

    Session deleteSession(User user, String session);

    /**
     *
     * @param user
     * @param session
     * @param role
     */
    void addActiveRole(User user, Session session, Role role);

    /**
     *
     * @param user
     * @param session
     * @param role
     */
    void dropActiveRole(User user, Session session, Role role);

    /**
     * 权限检查, 核心接口
     *
     * @param session
     * @param operation
     * @param resource
     * @return
     */
    Boolean checkAccess(Session session, Operation operation, Resource resource);
}
